#pragma once

#include <string>
#include <vector>
#include <cstdint>

// Token-level routing gate.
//
// Given the small model's last-layer hidden state for the current position (and,
// as a fallback, its next-token logits), decide whether the NEXT span should be
// generated by the cloud (large) model instead of the local (small) model.
//
// Two modes:
//   1. MLP mode    - a trained gate: Linear(n_embd -> H) -> ReLU -> Linear(H -> 1) -> sigmoid.
//                    Loaded from a simple binary weight file (see router_load_mlp).
//   2. Placeholder - when no weights are provided. Either a fixed random probability
//                    (route_random) or a confidence heuristic on the small model's logits
//                    (route when top-token probability < threshold, i.e. the small model
//                    is unsure -> defer to the big model).
struct router_config {
    std::string weights_path;   // path to MLP weights; empty => placeholder
    float       threshold = 0.5f;  // route when score > threshold
    float       route_random = -1.0f; // if in [0,1], ignore everything and route with this prob
};

struct router_decision {
    bool  route = false;
    float score = 0.0f;   // routing probability / confidence proxy in [0,1]
    const char * reason = "";
};

struct router {
    router_config cfg;

    // MLP weights (empty when in placeholder mode)
    int32_t n_embd  = 0;
    int32_t n_hidden = 0;
    std::vector<float> w1;  // [n_hidden * n_embd]
    std::vector<float> b1;  // [n_hidden]
    std::vector<float> w2;  // [n_hidden]
    float              b2 = 0.0f;
    bool   has_mlp = false;

    // deterministic PRNG state for route_random (avoids depending on global rng)
    uint64_t rng_state = 0x9e3779b97f4a7c15ULL;

    bool load_mlp(const std::string & path, std::string & err);

    // hidden: pointer to n_embd floats (may be null in pure-random mode)
    // logits: pointer to n_vocab floats for the heuristic fallback (may be null)
    router_decision decide(const float * hidden, int n_embd_in,
                           const float * logits, int n_vocab);
};
